### ISSUE TITLE
Not using GPU

### ISSUE THREAD

**Issue by Echolink50** [aihacker111/Efficient-Live-Portrait#3]
WIndows 10, RTX 2060 12GB. Install had an error with torchaudio so I looked in the issues and deleted torchaudio from the requirements.txt. Installed fine. Runs fine but no GPU and estimated time is 10 minutes for 3 second 78 frame example file. The Liveportrait main takes about 10 seconds for a 3 second video. Not sure what the issue is.

**Comment by aihacker111** [comment]
The between that onnx model , you run it on CPU only and you need compare with main Live Portrait in CPU as the same RAM not GPU ,
Also , we preparing for release TensorRT as well as aware than onnx

**Comment by Echolink50** [comment]
Sorry, I didn't understand that. What do I need to compare? Do I need to run it with -r for real time or something?

**Comment by aihacker111** [comment]
@Echolink50 Wait me update new model with handle GPU onnx, if you can't run it on onnx model , it seem like you install onnxruntime-gpu don't fit with your cuda and cudnn 

Follow this issues #2 : If you run onnxruntime successfully on GPU it'll raise error like this

**Comment by ultrafro** [comment]
@Echolink50 not sure if you had the same problem, but for me:

- gpu was not working on windows 10
- `conda activate ELivePortrait`
- `pip uninstall onnxruntime` 
- `pip uninstall onnxruntime-gpu`
- made sure the latest distributable was installed: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
- updated conda's redistributable:  `conda install conda-forge::vs2015_runtime`
- `pip install onnxruntime-gpu`
- then it worked. You can check by opening a python terminal: `python`
- and running: `>>> import onnxruntime as rt`
- `>>> rt.get_device()`
- result should be gpu

**Comment by Echolink50** [comment]
I did do pip uninstall onnxruntime and pip install onnxruntime but i didn't do the other stuff you mentioned. I will give it a try but from what people have been saying it's still not faster than the main repo. Seems trying to go straight to tensorRT is more worthwhile.

**Comment by aihacker111** [comment]
@Echolink50 TensorRT is faster than onnx , so the onnx model have some problem with speed inference since few year ago at many another repo, so just use it for fun or you can use with tensorRT for get faster
